name: Azure Static HTML Deploy

on:
  push:
    branches:
      - master  # oder main, je nach deinem Branch-Namen

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: webcloudsec
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
